#ifndef USART_CONFIG_H_
#define USART_CONFIG_H_

#define F_CPU 8000000UL

#define USART_BAUDRATE  9600
// USART_SPEED_NORMAL USART_SPEED_DOUBLE
#define USART_SPEED     USART_SPEED_NORMAL
// Transmitter or Receiver or Both
#define USART_DIRECTION USART_DIRECTION_BOTH
//INTERRUPT or POLLING
#define USART_INTERRUPT USART_INTERRUPT_POLLING


#define USART_STOPBITS  USART_STOPBITS_1
#define USART_PARITY    USART_PARITY_DISABLED
#define USART_MODE      USART_MODE_ASYNC
#define USART_DATA_SIZE USART_DATA_SIZE_8
#define USART_CLOCK_POL USART_CLOCK_POL_RISING_TX_FALLING_RX


#endif /* USART_CONFIG_H_ */
