#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

#define TIMER0_WAVEFORM_GENERATION_MODE NORMAL
#define TIMER0_COMPARE_OUTPUT_MODE NORMAL_PORT_OPERATION
#define TIMER0_PRESCALER PRESCALER_8
#define TIMER0_INTERRUPT_ENABLE OCIE0




#endif /* TIMER_CONFIG_H_ */
