#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_




#define TIMER0_INTERRUPT_ENABLE OCIE0

#define F_CPU 8000000UL

#define OC_Mode DISCONNECTED

#define TIMER0_WAVEFORM_GENERATION_MODE CTC

#define TIMER0_PRESCALER PRESCALER_64

#define TIMER0_COMPARE_OUTPUT_MODE NORMAL_PORT_OPERATION


#endif /* TIMER_CONFIG_H_ */
